const bookinfo =[
  {auteur:"Alice Zentier",
  info:"L’Algérie dont est originaire sa famille n’a longtemps été pour Naïma qu’une toile de fond sans grand intérêt. Pourtant, dans une société française traversée par les questions identitaires, tout semble vouloir la renvoyer à ses origines. Mais quel lien pourrait-elle avoir avec une histoire familiale qui jamais ne lui a été racontée ? Son grand-père Ali, un montagnard kabyle, est mort avant qu’elle ait pu lui demander pourquoi l’Histoire avait fait de lui un « harki ». Yema, sa grand-mère, pourrait peut-être répondre mais pas dans une langue que Naïma comprenne. Quant à Hamid, son père, arrivé en France à l’été 1962 dans les camps de transit hâtivement mis en place, il ne parle plus de l’Algérie de son enfance. "
},
{auteur:"Eric Vuillard ",
 info:"L’Allemagne nazie a sa légende. On y voit une armée rapide, moderne, dont le triomphe parait inexorable. Mais si au fondement de ses premiers exploits se découvraient plutôt des marchandages, de vulgaires combinaisons d’intérêts ? Et si les glorieuses images de la Wehrmacht entrant triomphalement en Autriche dissimulaient un immense embouteillage de panzers ? Une simple panne ! Une démonstration magistrale et grinçante des coulisses de l’Anschluss par l’auteur de Tristesse de la terre et de 14 juillet."
},
{auteur:"Philippe BESSON",
 info:"Quand j'étais enfant, ma mère ne cessait de me répéter :  Arrête avec tes mensonges.  J'inventais si bien les histoires, paraît-il, qu'elle ne savait plus démêler le vrai du faux. J'ai fini par en faire un métier, je suis devenu romancier. Aujourd'hui, voilà que j'obéis enfin à ma mère : je dis la vérité. Pour la première fois. Dans ce livre. Autant prévenir d'emblée : pas de règlement de comptes, pas de violence, pas de névrose familiale."},
{auteur:"Laetitia Colombani",
 info:"Trois femmes, trois vies, trois continents. Une même soif de liberté. Inde. Smita est une Intouchable. Elle rêve de voir sa fille échapper à sa condition misérable et entrer à l’école. Sicile. Giulia travaille dans l’atelier de son père. Lorsqu’il est victime d’un accident, elle découvre que l’entreprise familiale est ruinée. Canada. Sarah, avocate réputée, va être promue à la tête de son cabinet quand elle apprend qu’elle est gravement malade. Liées sans le savoir par ce qu’elles ont de plus intime et de plus singulier, Smita, Giulia et Sarah refusent le sort qui leur est destiné et décident de se battre. Vibrantes d’humanité, leurs histoires tissent une tresse d’espoir et de solidarité"},
{auteur:"Hervé Roullet",
 info:"Quelle trajectoire extraordinaire que celle de Joséphine Bakhita, l'esclave soudanaise devenue sainte, gloire de l'Afrique et patronne des opprimés ! Enlevée par des négriers à l'âge de neuf ans, vendue plusieurs fois à des maîtres cruels, battue et torturée, elle est providentiellement tirée de l'esclavage par un consul italien qui l'achète et l'emmène en Italie. Bakhita y rencontre le Dieu d'Amour, son seul maître et Seigneur, reçoit le baptème et entend l'appel du Christ à lui consacrer sa vie. Entrée chez les soeurs canossiennes, elle suit pas à pas, pendant près d'un demi-siècle, une petite voie spirituelle étinnamment proche de celle de sa contemporaine, Thérèse de Lisieux.."},
{auteur:"Yannick Haenel",
 info:"Un homme a écrit un énorme scénario sur la vie de Herman Melville : The Great Melville, dont aucun producteur ne veut. Un jour, on lui procure le numéro de téléphone du grand cinéaste américain Michael Cimino, le réalisateur mythique de Voyage au bout de l'enfer et de La Porte du paradis. Une rencontre a lieu à New York : Cimino lit le manuscrit. S’ensuivent une série d’aventures rocambolesques entre le musée de la Chasse à Paris, l’île d’Ellis Island au large de New York, et un lac en Italie. On y croise Isabelle Huppert, la déesse Diane, un dalmatien nommé Sabbat, un voisin démoniaque et deux moustachus louches ; il y a aussi une jolie thésarde, une concierge retorse et un très agressif maître d’hôtel"},
{auteur :"Hannelore Cayre",
 info:"Comment, lorsqu'on est une femme seule, travailleuse avec une vision morale de l'existence... qu'on a trimé toute sa vie pour garder la tête hors de l'eau tout en élevant ses enfants... qu'on a servi la justice sans faillir, traduisant des milliers d'heures d'écoutes téléphoniques avec un statut de travailleur au noir... on en arrive à franchir la ligne jaune ? Rien de plus simple, on détourne une montagne de cannabis d'un Go Fast et on le fait l'âme légère, en ne ressentant ni culpabilité ni effroi, mais plutôt... disons... un détachement joyeux. Et on devient la Daronne."},
{auteur:"Jakuta Alikavazovic",
 info:"Mais à l'hôtel il en va autrement, l'hôtel est le lieu de leur intimité, celui où ils se regardent, où ils s'approchent, farouches et fiers, jusqu'à sentir rayonner la chaleur de l'autre, de sa peau, avant même de l'avoir touchée. Avant même de l'avoir vue, cette peau qui n'attend que la caresse. Paul, étudiant et gardien d'hôtel, est fasciné par Amélia, l'occupante de la chambre 313. Tout chez elle est un mystère, ses allées et venues comme les rumeurs qui l'entourent. Lorsque Amélia disparaît, Paul ignore qu'elle s'est rendue à Sarajevo, à la recherche de sa mère, d'un pan inconnu de son histoire – et de la nôtre : celle de la dernière guerre civile qui a déchiré l'Europe."},
{auteur:"Philippe JAENADA",
 info:"Un matin d'octobre 1941, dans un château sinistre au fin fond du Périgord, Henri Girard appelle au secours : dans la nuit, son père, sa tante et la bonne ont été massacrés à coups de serpe. Il est le seul survivant. Toutes les portes étaient fermées, aucune effraction n'est constatée. Dépensier, arrogant, violent, le jeune homme est l'unique héritier des victimes. Deux jours plus tôt, il a emprunté l'arme du crime aux voisins. Pourtant, au terme d'un procès retentissant (et trouble par certains aspects), il est acquitté et l'enquête abandonnée. Alors que l'opinion publique reste convaincue de sa culpabilité, Henri s'exile au Venezuela. Il rentre en France en 1950 avec le manuscrit du Salaire de la peur, écrit sous le pseudonyme de "},
]

export default bookinfo;
